In [1]:
import torch

In [2]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [3]:
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [4]:
print(x.shape)

torch.Size([2, 5])


In [5]:
y = torch.rand([2,5])
print(y)

tensor([[0.1588, 0.2246, 0.0337, 0.8432, 0.7765],
        [0.6975, 0.6834, 0.5544, 0.0275, 0.5083]])


In [6]:
y.view([1,10])

tensor([[0.1588, 0.2246, 0.0337, 0.8432, 0.7765, 0.6975, 0.6834, 0.5544, 0.0275,
         0.5083]])

In [7]:
y

tensor([[0.1588, 0.2246, 0.0337, 0.8432, 0.7765],
        [0.6975, 0.6834, 0.5544, 0.0275, 0.5083]])

In [8]:
y = y.view([1,10])

In [9]:
y

tensor([[0.1588, 0.2246, 0.0337, 0.8432, 0.7765, 0.6975, 0.6834, 0.5544, 0.0275,
         0.5083]])